const style = {
  shell: {
    display: "flex",
    minHeight: "100vh",
    background: "var(--bg-base, #0a0c10)",
  },
  sidebar: {
    position: "fixed",
    top: 0,
    left: 0,
    height: "100vh",
    background: "var(--bg-surface, #10131a)",
    borderRight: "1px solid var(--border, #1c2030)",
    display: "flex",
    flexDirection: "column",
    transition: "width .22s ease",
    zIndex: 100,
    overflow: "hidden",
  },
  sidebarLogo: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "18px 16px 16px",
    minHeight: "64px",
  },
  logoIcon: {
    width: "32px",
    height: "32px",
    background: "var(--accent-dim, #1a3a26)",
    border: "1px solid rgba(74,222,128,.25)",
    borderRadius: "8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  logoText: {
    fontFamily: "var(--font-display, 'Syne', sans-serif)",
    fontWeight: 800,
    fontSize: "16px",
    color: "var(--text-primary, #e8eaf0)",
    flex: 1,
    whiteSpace: "nowrap",
  },
  collapseBtn: {
    background: "none",
    border: "1px solid var(--border, #1c2030)",
    borderRadius: "6px",
    color: "var(--text-muted, #4b5563)",
    cursor: "pointer",
    padding: "4px 6px",
    display: "flex",
    alignItems: "center",
    flexShrink: 0,
    transition: "color .15s, background .15s",
  },
  divider: {
    height: "1px",
    background: "var(--border-subtle, #161926)",
    margin: "0 12px",
  },
  nav: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
    padding: "12px 8px",
  },
  navSection: {
    fontSize: "10px",
    fontWeight: 600,
    color: "var(--text-muted, #4b5563)",
    textTransform: "uppercase",
    letterSpacing: ".7px",
    padding: "0 6px",
    marginBottom: "6px",
    display: "block",
  },
  navItem: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    borderRadius: "8px",
    textDecoration: "none",
    color: "var(--text-secondary, #9ca3af)",
    fontSize: "13.5px",
    fontWeight: 500,
    transition: "background .15s, color .15s",
    whiteSpace: "nowrap",
  },
  navItemActive: {
    background: "var(--accent-muted, rgba(74,222,128,.12))",
    color: "var(--accent, #4ade80)",
  },
  navIcon: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
  },
  navLabel: {
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  userArea: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  userInfo: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    minWidth: 0,
    flex: 1,
  },
  userAvatar: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    background: "var(--accent-dim, #1a3a26)",
    border: "1px solid rgba(74,222,128,.25)",
    color: "var(--accent, #4ade80)",
    fontFamily: "var(--font-display, 'Syne', sans-serif)",
    fontWeight: 700,
    fontSize: "13px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  userName: {
    fontSize: "13px",
    fontWeight: 500,
    color: "var(--text-primary, #e8eaf0)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    margin: 0,
  },
  userRole: {
    fontSize: "11px",
    color: "var(--text-muted, #4b5563)",
    textTransform: "capitalize",
    margin: 0,
  },
  logoutBtn: {
    background: "none",
    border: "1px solid var(--border, #1c2030)",
    borderRadius: "7px",
    color: "var(--text-muted, #4b5563)",
    cursor: "pointer",
    padding: "6px 7px",
    display: "flex",
    alignItems: "center",
    flexShrink: 0,
    transition: "color .15s, border-color .15s, background .15s",
  },
  main: {
    flex: 1,
    minHeight: "100vh",
    transition: "margin-left .22s ease",
  },
  pageBody: {
    padding: "var(--space-8, 32px)",
  },
};

export default style;